### ISSUE TITLE
not working + wrong label on Twitter Settings Panel

### ISSUE THREAD

**Issue by cwerge** [kunicmarko20/Another-Twitter-Plugin#1]
Hi,

I installed you plugin and went through the activation process - unfortunately the result is a blank space. All it creates is a class-less empty div-container (see screenshot).

![screenshot empty div](https://cloud.githubusercontent.com/assets/15015362/15607122/baee65d4-2410-11e6-957a-382c17419b33.png) - "oho" is how I found out it's that part of your php code.

I checked the settings twice, so I guess they are ok. There had been an error first that went unnoticed so an error message would be helpful in this case, too.

Also the Twitter Settings Panel calls the Consumer (Key and Secret) Customer and the input area is to small to see the whole key - this makes checking your input rather difficult.

Is it normal that twitter.json is practically empty - sorry I really don't speak json...

I would so love this plugin to work!
Christina

**Comment by kunicmarko20** [comment]
Can you provide me with picture of your "dashboard" and "display style" page, you can email it to me if you don't want to post here, about the input area being too small, I will update that.

**Comment by cwerge** [comment]
Hi Marko,

Thank you for your fast answer! Here are the screenshots. I have altered nothing in the style code - I do such things usually last.

Christina

**Comment by kunicmarko20** [comment]
You didn't attach any photos, did you add usernames or hashtags to plugin settings? Did you choose between username or hashtag? Did you press update button in dashboard ?

**Comment by cwerge** [comment]
Hi,
the attached pngs apparently didn't make it with the email. Sorry. And yes, I did all of the above mentioned.
![dashboard](https://cloud.githubusercontent.com/assets/15015362/15642747/95635596-2649-11e6-8adc-8d31f4307534.png)
![display style](https://cloud.githubusercontent.com/assets/15015362/15642748/958df328-2649-11e6-9f7d-be5c7fbf7c6f.png)

**Comment by kunicmarko20** [comment]
Ok, the problem is you added @ before username and you don't need to add @ or # , I should add a Note in page where you add username/hashtags

**Comment by cwerge** [comment]
I tried it without the @ and pressed the update button - still the same result: an empty div with an unnamed class.

It did solve the empty json.

**Comment by kunicmarko20** [comment]
So json is not empty anymore, how did you add shortcode ? did  you add it to your code or post ?

**Comment by cwerge** [comment]
by shortcode. It seems to have just needed a bit more patience ... rechecked the page and now it works. Thank you!

**Comment by kunicmarko20** [comment]
Not a problem, glad to help, will update in few days with larger fields and note for # and @.
